name: Update Language Statistics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check STATS_TOKEN
        env:
          STATS_TOKEN: ${{ secrets.STATS_TOKEN }}
        run: |
          if [ -z "$STATS_TOKEN" ]; then
            echo "❌ STATS_TOKEN is EMPTY"
            exit 1
          else
            echo "✅ STATS_TOKEN is available"
          fi

      - uses: StefVuck/Github-Language-Stats@v1.2.0
        with:
          github_token: ${{ secrets.STATS_TOKEN }}
          visualization_types: "leaderboard"
          output_path: "stats"
